### ISSUE TITLE
Create github page

### ISSUE THREAD

**Issue by ngiangre** [AndrewC160/ROMOPOmics#7]
https://pages.github.com/

**Comment by ngiangre** [comment]
https://kbroman.org/simple_site/pages/project_site.html

**Comment by AndrewC160** [comment]
I translated that "demo" script into GitHub format so that it spits out a README.md file. This should hold us over for now, though it certainly can use some editing. Also may want some more figures describing the data model, maybe something showing the various tables interacting. I can draw up one similar to the network graphs I featured in the Shiny app.

**Comment by ngiangre** [comment]
It's great! I'll see what I can do in the meantime
